import { query } from '../config/db.js'
function normalize(value) { return String(value || '').trim().replace(/^@/, '').toLowerCase() }
const WINNING_LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
function outcome(moves, match) { const board = Array(9).fill(null); moves.forEach((move) => { if (Number.isInteger(move.index) && move.index >= 0 && move.index < 9) board[move.index] = move.player }); for (const [a,b,c] of WINNING_LINES) if (board[a] && board[a] === board[b] && board[a] === board[c]) return { status: 'finished', result: board[a] === 'X' ? 'x_win' : 'o_win', winnerUsername: board[a] === 'X' ? match.player_x_username : match.player_o_username }; return moves.length === 9 ? { status: 'finished', result: 'draw', winnerUsername: null } : { status: 'active', result: null, winnerUsername: null } }
export const LiveModel = {
  async getChallenges() { const { rows } = await query('SELECT * FROM live_challenges ORDER BY created_at DESC'); return rows },
  async createChallenge({ challengerUsername, opponentUsername, wagerAmount }) { const { rows } = await query(`INSERT INTO live_challenges (challenger_username, opponent_username, wager_amount, status) VALUES ($1, $2, $3, 'pending') RETURNING *`, [challengerUsername, opponentUsername, wagerAmount]); return rows[0] },
  async acceptChallenge(id) { await query('UPDATE live_challenges SET status = $1, accepted_at = $2 WHERE id = $3', ['accepted', Date.now(), id]); const challenge = await this.getChallengeById(id); if (!challenge) return null; const existing = await this.getMatchByChallengeId(id); if (existing) return { challenge, match: existing }; const { rows } = await query(`INSERT INTO live_matches (challenge_id, player_x_username, player_o_username, wager_amount, status, moves) VALUES ($1, $2, $3, $4, 'active', '[]') RETURNING *`, [id, challenge.challenger_username, challenge.opponent_username, challenge.wager_amount]); await query('UPDATE live_challenges SET match_id = $1 WHERE id = $2', [rows[0].id, id]); return { challenge: await this.getChallengeById(id), match: rows[0] } },
  async getMatchByChallengeId(id) { const { rows } = await query('SELECT * FROM live_matches WHERE challenge_id = $1', [id]); return rows[0] || null },
  async declineChallenge(id) { await query("UPDATE live_challenges SET status = 'declined' WHERE id = $1", [id]); return this.getChallengeById(id) },
  async getPendingChallenges(username) { const value = normalize(username); const params = value ? [value] : []; const where = value ? " WHERE status = 'pending' AND (lower(replace(trim(challenger_username),'@','')) = $1 OR lower(replace(trim(opponent_username),'@','')) = $1)" : " WHERE status = 'pending'"; const { rows } = await query(`SELECT * FROM live_challenges${where} ORDER BY created_at DESC`, params); return rows },
  async getChallengeById(id) { const { rows } = await query('SELECT * FROM live_challenges WHERE id = $1', [id]); return rows[0] || null },
  async getMatches() { const { rows } = await query('SELECT * FROM live_matches ORDER BY created_at DESC'); return rows },
  async getMatchById(id) { const { rows } = await query('SELECT * FROM live_matches WHERE id = $1', [id]); return rows[0] || null },
  async recordMove({ matchId, playerUsername, index }) { const match = await this.getMatchById(matchId); if (!match) throw new Error('Match not found'); let moves = []; try { moves = match.moves ? JSON.parse(match.moves) : [] } catch {} if (moves.some((move) => Number(move.index) === index)) throw new Error('Cell already occupied'); const role = moves.length % 2 === 0 ? 'X' : 'O'; const expected = role === 'X' ? match.player_x_username : match.player_o_username; if (normalize(playerUsername) !== normalize(expected)) throw new Error('It is not this player\'s turn'); const next = [...moves, { index, player: role, username: playerUsername }]; const result = outcome(next, match); const { rows } = await query('UPDATE live_matches SET moves = $1, status = $2, result = $3, winner_username = $4 WHERE id = $5 RETURNING *', [JSON.stringify(next), result.status, result.result, result.winnerUsername, matchId]); return rows[0] },
  async forfeitMatch({ matchId, leavingUsername }) { const match = await this.getMatchById(matchId); if (!match) throw new Error('Match not found'); if (match.status === 'finished') return match; const leaving = normalize(leavingUsername); const winner = leaving === normalize(match.player_x_username) ? match.player_o_username : leaving === normalize(match.player_o_username) ? match.player_x_username : null; if (!winner) throw new Error('Player not in match'); const result = normalize(winner) === normalize(match.player_x_username) ? 'x_win' : 'o_win'; const { rows } = await query('UPDATE live_matches SET status = $1, result = $2, winner_username = $3, finished_at = $4 WHERE id = $5 RETURNING *', ['finished', result, winner, Date.now(), matchId]); return rows[0] },
}
