import { query } from '../config/db.js'
function normalize(username) { return String(username || '').trim().replace(/^@/, '').toLowerCase() }
const fields = 'id, username, balance, status, selected_bet_amount'
export const PlayerModel = {
  async findAll() { const { rows } = await query(`SELECT ${fields} FROM players WHERE is_demo = 0 AND status = 'online' ORDER BY id ASC`); return rows },
  async findById(id) { const { rows } = await query(`SELECT ${fields} FROM players WHERE id = $1`, [id]); return rows[0] || null },
  async findByUsername(username) { const value = normalize(username); if (!value) return null; const { rows } = await query(`SELECT ${fields} FROM players WHERE lower(replace(trim(username), '@', '')) = $1`, [value]); return rows[0] || null },
  async findByBetAmount(amount) { const value = Number(amount); if (!Number.isFinite(value) || value <= 0) return []; const { rows } = await query(`SELECT ${fields} FROM players WHERE is_demo = 0 AND selected_bet_amount = $1 AND selected_bet_amount > 0 AND status = 'online' ORDER BY id ASC`, [value]); return rows },
  async create({ username, balance = 0, status = 'online', selectedBetAmount = null }) { const { rows } = await query(`INSERT INTO players (username, balance, status, selected_bet_amount, is_demo) VALUES ($1, $2, $3, $4, 0) RETURNING ${fields}`, [normalize(username), balance, status, selectedBetAmount == null ? null : Number(selectedBetAmount)]); return rows[0] },
  async upsertByUsername({ username, balance, status = 'online', selectedBetAmount = null, updateBalance = false }) { const existing = await this.findByUsername(username); if (existing) { const nextBalance = updateBalance ? Number(balance ?? existing.balance ?? 0) : existing.balance; const selected = Number(selectedBetAmount); const nextBet = Number.isFinite(selected) && selected > 0 ? selected : null; await query(`UPDATE players SET balance = $1, status = $2, selected_bet_amount = $3 WHERE lower(replace(trim(username), '@', '')) = $4`, [nextBalance, status || existing.status, nextBet, normalize(username)]); return this.findByUsername(username) } return this.create({ username, balance: Number(balance ?? 0), status, selectedBetAmount }) },
  async clearBet(username) { const value = normalize(username); if (!value) return null; await query("UPDATE players SET selected_bet_amount = NULL WHERE lower(replace(trim(username), '@', '')) = $1", [value]); return this.findByUsername(value) },
  async goOnline({ username, balance }) { const value = normalize(username); if (!value) return null; const existing = await this.findByUsername(value); if (existing) { await query("UPDATE players SET status = 'online', balance = $1, is_demo = 0 WHERE lower(replace(trim(username), '@', '')) = $2", [Number(balance) || 0, value]); return this.findByUsername(value) } return this.create({ username: value, balance: Number(balance) || 0 }) },
  async goOffline(username) { const value = normalize(username); if (value) await query("UPDATE players SET status = 'offline', selected_bet_amount = NULL WHERE lower(replace(trim(username), '@', '')) = $1", [value]) },
}
